### ISSUE TITLE
No way to configure http calls in Angular client for CORS requests

### ISSUE THREAD

**Issue by ghost** [fullscale/elastic.js#10]
So for my version, I have CORS enabled and for communicating with my API, I need to set some custom headers for authentication, so I do so with the common headers in Angular, but that conflicts with the calls to Elastic as it is not configured to accept those headers, so I need to remove them. Locally when I call it, I just pass a transformRequest, but with elastic.js, there's no way to do that. It appears to be a minor change to allow that, here is my proposed change in elastic-angular-client.js, let me know what you think.

https://gist.github.com/dariusriggins/5255188

**Comment by mattweber** [comment]
Looks good.  I will get this into the next release.  Thanks!

**Comment by maharg101** [comment]
Thanks both for this :D

Any ETA on the next release ?

**Comment by mattweber** [comment]
Next release will be shortly after ES 0.90 GA.   I will probably have this ready within a few days.

**Comment by maharg101** [comment]
excellent thanks !
