### ISSUE TITLE
No API for multi search

### ISSUE THREAD

**Issue by ghost** [fullscale/elastic.js#12]
Maybe I'm missing it, but this is one of the few calls I couldn't find. I have a number of instances where this saves me some time, not sure how difficult it would be to implement.

http://www.elasticsearch.org/guide/reference/api/multi-search/

Not sure if it will be useful, but I ran into some issues when implementing it myself via Angular.

http://stackoverflow.com/questions/15481445/post-new-line-in-json-for-msearch-in-elasticsearch

**Comment by ghost** [comment]
So I put some sample code in to see if I could get it working, and I did manage too with a fairly clean looking implementation. Let me know if you think it's possible to get this included in the next release, or something similar.

https://gist.github.com/dariusriggins/5294932

**Comment by mattweber** [comment]
This is definitely on the roadmap along with bulk indexing support.  Unfortunately, I am not sure if it will make the next release or not.  This requires a bit more logic than what is in the gist you provided above.  Multi-search supports submitting multiple requests against any number of indicies, types, all with different settings.  Basically we need to submit multiple `ejs.Request` objects in a single call.

My initial thoughts are to create an `ejs.MultiRequest` object that holds any number of `ejs.Request` objects.  Then there will be a doMultiSearch method that uses the index/type/parent/routing information from each Request to craft the headers and the request _self() for the actual request body.   Beyond this, it also needs to support setting the search type (ie. count), etc.

**Comment by ghost** [comment]
That makes sense, I assumed I probably accounted for exactly 1 use case. I think the MultiRequest route sounds good, a little more verbose but that's fine. Let me know if you want me to take a stab at it and submit a PR, otherwise I'll just hang back and wait on official support for it.

**Comment by mattweber** [comment]
You can give it a start and open a PR.  I can then work off that if any changes are needed.  Please work from a topic branch so we can rebase/merge easily.  Also no 3rd party dependencies ( underscore, jquery) please.  Try to use the methods I have in utils.  Thanks!

**Comment by ghost** [comment]
Haven't had a chance to work on this yet, might wait till the 0.9 release drops and start from there, unless you have time before me.

**Comment by mattweber** [comment]
Just pushed support for multi-search.  Just create a `ejs.MultiSearchRequest` object then push multiple `ejs.Request` objects into it using the `requests` method.  There are other options depending on what you need to do, have a look at the tests for some examples.
