### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by Jagdeep1** [fullscale/elastic.js#2]
Hi,

I am using ES for more than a year now. This library draws my interest and looks very promising.  I have never used node.js but I do want to use this library for its jquery client.

Can I use it without node.js?
I have tried running examples which you have given but its throwing "Request header field Content-Type is not allowed by Access-Control-Allow-Headers." error on chrome.

A pure jquery based example will be really helpful.

Regards
Jagdeep

**Comment by egaumer** [comment]
Yes, elastic.js is agnostic in that it can run on the server (node.js) or client (jquery). There's a pure jQuery [example](https://github.com/fullscale/elastic.js/tree/master/examples/jquery) included in the examples directory.

The issue you're seeing is from the [Same Origin Policy](http://en.wikipedia.org/wiki/Same_origin_policy). Elasticsearch supports [CORS](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing). Have a look at this [issue](https://github.com/elasticsearch/elasticsearch/issues/828) for more background on CORS support in elasticsearch.

**Comment by Jagdeep1** [comment]
Hey thanks a lot for your quick response. 

I downloaded latest version of ES and Same Origin Policy issue is gone :+1: 
Will play around with jquery client now :)
