### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by porjo** [fullscale/elastic.js#24]
The [Apache Lucene doco](http://lucene.apache.org/core/old_versioned_docs/versions/2_9_1/queryparsersyntax.html#Escaping%20Special%20Characters) lists the following special characters that need to be escaped with `\` in query strings:

```
+ - && || ! ( ) { } [ ] ^ " ~ * ? : \
```

I've also found that `/` needs escaping.

The problem I have is knowing when to escape. For example, an unescaped `~` on it's own produces an 'internal server error' from ES but when appended to a word e.g. `blah~` I get a result.

 Is this something that Elastic.js can handle for me, or do I need to create an ellaborate regex?

**Comment by mattweber** [comment]
If you are using a query that takes lucene query syntax it needs to be escaped.  I imagine you are using a `QueryStringQuery` and passing the user's input directly as the query string and running into parsing errors.  Typically, if you are just passing user queries it is best to use a `MatchQuery` or `MultiMatchQuery` which does not parse the query string or need these characters escaped.

**Comment by porjo** [comment]
OK, thanks - looks like I need to do some more reading :smile:
