### ISSUE TITLE
Bower support seems off

### ISSUE THREAD

**Issue by ghost** [fullscale/elastic.js#25]
So on a project I just did bower install elastic.js, and got most of the repo copied, with the exception of the dist folder, which in this case is the only one I actually care about. This is on bower 0.9.2, and it got v 1.1.1 of elastic.js.

**Comment by mattweber** [comment]
Can you please try again?  I just tested and the dist folder with the expected files were pulled in just fine.

**Comment by ghost** [comment]
You're right, hmm, that's unfortunate though, my sublime project is ignoring dist as that's what the default Angular project uses for the release build, so .tmp and dist are ignored to make the project reasonable. Would you be open to changing the folder structure at all? As far as bower goes, I find it really nice with layouts like lodash and angular, whereas they have what you have in the dist folder and in bower.json ignore literally everything else, which I think is typically what most people expect when using it.

**Comment by mattweber** [comment]
Unfortunately no.  It looks like angular created a separate repository specifically for bower.  I might be able to do something like this for the next release.

**Comment by ghost** [comment]
No worries, I'm fine now that I know it's there, just got thrown off by it being missing. I think the contents may be part of a bigger question around bower. More or less, are we expected to add the components to source control or not. If so, I think this structure is a bit heavy.

**Comment by ghost** [comment]
One interesting option seen here is to make the dist folder a subrepository. That way people can still clone the full thing, still download directly from GitHub, but the Bower link would point to the subrespository. https://github.com/stackfull/angular-virtual-scroll
