### ISSUE TITLE
heap stats

### ISSUE THREAD

**Issue by porjo** [fullscale/elastic.js#29]
Using curl I can get statistics about the heap e.g.

``` bash
$ curl -s -XGET 'http://localhost:9200/_cluster/nodes/stats?jvm=true&pretty=true' | grep heap
          "heap_used" : "4.4gb",
          "heap_used_in_bytes" : 4777105152,
          "heap_committed" : "6.9gb",
          "heap_committed_in_bytes" : 7446462464,
          "non_heap_used" : "41.7mb",
          "non_heap_used_in_bytes" : 43812696,
          "non_heap_committed" : "63mb",
          "non_heap_committed_in_bytes" : 66142208,
```

I'd like to know how I can get the same stats using Elastic.js. I've tried using [`NodeStats` module](http://docs.fullscale.co/elasticjs/ejs.NodeStats.html) and setting `.jvm(true)` and also `.all(true)` however the result does not contain any stats about the heap.

**Comment by mattweber** [comment]
Can you try again?  I just executed this and it worked just fine:

``` javascript
ejs.NodeStats().jvm(true).doStats(function (stats) {
        for (var nodeId in stats.nodes) {
            console.log(stats.nodes[nodeId].jvm.mem.heap_used);
        }
});
```

**Comment by porjo** [comment]
I tried your code, but get this error:

```
TypeError: stats.nodes[nodeId].jvm is undefined
console.log(stats.nodes[nodeId].jvm.mem.heap_used);
```

I've pasted the JSON that I receive back on [pastebin.com](http://pastebin.com/MbL3Tjdf)

My environment is Ubuntu 12.04 64bit, ES 0.90.0, latest `elastic.min.js`.

**Comment by mattweber** [comment]
Did you get this working?  I am unable to reproduce.

**Comment by porjo** [comment]
No, still not working. I've captured the TCP traffic using tcpdump between my browser and the Elasticsearch server.

I can see the HTTP requests going out are `GET /_nodes/stats?[object%20Object] HTTP/1.1` . That looks wrong to me - you wouldn't expect to see a literal `[object%20Object]` in the ascii string would you?

If there are any specific checks you can suggest, I'd be happy to try them.

**Comment by mattweber** [comment]
What client are you using?

**Comment by porjo** [comment]
Firefox 23 on Win7. I've also tested on Chrome with same result.

Not sure if relevent, the JS includes at the top of my index.html are:

```
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/elastic.min.js"></script>
<script src="js/elastic-jquery-client.min.js"></script>
<script src="js/moment.min.js"></script>
```

**Comment by mattweber** [comment]
It might be something in the jQuery client, let me try to reproduce.

**Comment by mattweber** [comment]
Fixed, it was a bug in the jQuery client.   Please pull in the new elastic-jquery-client.min.js file and things should work as expected.  Thanks for reporting this!

**Comment by porjo** [comment]
Thanks, works fine now!
