### ISSUE TITLE
No method for bulk indexing

### ISSUE THREAD

**Issue by cimi** [fullscale/elastic.js#30]
There seems to be no correspondent for the [bulk](http://www.elasticsearch.org/guide/reference/api/bulk/) API call.

I need this in a node client so I can populate a test ES install for benchmarking. I've successfuly used `Document.doIndex`, but it's too slow to be sending documents one by one. I notice this is present in https://github.com/phillro/node-elasticsearch-client so I'll switch to that for now.

**Comment by mattweber** [comment]
This is on the TODO list and will be one of the next features implemented.

**Comment by mattweber** [comment]
This is not going to happen now that [official javascript client](http://elasticsearch.github.io/elasticsearch-js/index.html) has been released.   The next version of elastic.js will remove all low-level client support and offer integration with the official client.  Bulk indexing is supported in the official client.
