### ISSUE TITLE
Problem with TermSuggester

### ISSUE THREAD

**Issue by iulia-pasov** [fullscale/elastic.js#31]
Hello,

I tried the term suggester and I always get the "term" option before the text in the suggest request, which generates an error in Elastic Search.

e.g. For 

```
ejs.TermSuggester("my_suggestion")
            .text("geographoc")
            .field("title");
```

The suggest request will be: 

```
"suggest":{"my_suggestion":{"term":{"field":"title"}, "text":"geographoc"}} 
```

instead of: 

```
"suggest":{"my_suggestion":{"text":"geographoc", "term":{"field":"title"}}} 
```

Thanks,
Iulia

**Comment by mattweber** [comment]
What version of elasticsearch are you using?  I have tested with 0.90.3 and everything works as expected.

**Comment by mattweber** [comment]
As expected means it doesn't matter what order text or term option come in the suggest request.

**Comment by iulia-pasov** [comment]
I've been working with ES 0.90.2. I'll switch to 0.90.3. Thanks for the reply.
