### ISSUE TITLE
grunt reports "Use the function form of "use strict"."

### ISSUE THREAD

**Issue by synhershko** [fullscale/elastic.js#33]
When using the elastic.js angular client with ng-boilerplate grunt reports this warning

I solved it by simply adding /*jslint node: true */ before 'use strict';

**Comment by mattweber** [comment]
What version of grunt are you using?  I am using the following versions and don't experience any warnings.

grunt@0.4.1
grunt-contrib-jshint@0.5.4

**Comment by synhershko** [comment]
grunt -version outputs grunt-cli v0.1.9. I _think_ I used npm to install this on my Mint machine.

**Comment by mattweber** [comment]
Unable to reproduce.  Please use latest versions of grunt.  You can use `npm install` to get all the recommended versions.
