### ISSUE TITLE
Make Elastic.js work with dataTables

### ISSUE THREAD

**Issue by mashinista** [fullscale/elastic.js#34]
Hi, 
Thanks for elastic.js. I have a question/request for a useful feature that could make elastic.js a better tool. I want to display my json results in a table using https://datatables.net/ that adds advanced interaction controls to any HTML table. Some help with how to accomplish this with elastic.js and datatables data sources and server side processing is greatly appreciated. Thanks

**Comment by brubrant** [comment]
Not the maintainer here, but, I can say this is not totally related to elastic.js _per se_. There are several approaches you could take. I would use one of the following:
- Create an API on your server that returns a JSON with the elasticseach "hits", and use [JQuery Ajax](http://api.jquery.com/jQuery.get/) to get this JSON and generate your table using DataTables
- You could generate the table on the back end using some templating language (like [Jade](http://jade-lang.com)) and apply the script on this table (on the front end). 

The seccond would be better for SEO pourposes.

**Comment by mattweber** [comment]
Elasticjs does not do any post-processing on the results returned from elasticsearch.  You can easily execute a search and then in the result handler perform any processing you want.  In this case, it would be to use the data tables api to add the results to your table (using their api and probably the `fnAddData` method).
