### ISSUE TITLE
Add support for Function Score Query

### ISSUE THREAD

**Issue by stonor** [fullscale/elastic.js#36]
It looks like the Function Score Query is supposed to replace a handful of custom scoring queries in Elasticsearch.

It would be nice with support for that in elastic.js.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

**Comment by mattweber** [comment]
Yes, I agree that we should support this.  I will try and get it in before the next release.

**Comment by smitt04** [comment]
whats the progress on this?

**Comment by mattweber** [comment]
Just pushed this support, see 96ffc1a704.  Here are some examples based on the [examples found in the official documentation](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html).

Custom Score

```
ejs.FunctionScoreQuery()
  .boostMode('replace')
  .query(ejs.MatchAllQuery())
  .function(ejs.ScriptScoreFunction()
              .script('_score * doc["my_numeric_field"].value / pow(param1, param2)')
              .params({'param1': 2, 'param2': 3.1}));
```

Custom Filter Score

```
ejs.FunctionScoreQuery()
  .functions([
    ejs.BoostFactorScoreFunction(3).filter(ejs.TermFilter('field', 'value')),
    ejs.ScriptScoreFunction()
      .script('_score * doc["my_numeric_field"].value / pow(param1, param2)')
      .params({'param1': 2, 'param2': 3.1})])
  .query(ejs.MatchAllQuery())
  .scoreMode('first');
```

The Detailed Example

```
ejs.FunctionScoreQuery()
  .functions([
    ejs.DecayScoreFunction('price').linear().origin(0).scale(20),
    ejs.DecayScoreFunction('location').exp()
      .origin(ejs.GeoPoint([12, 11])).scale('2km')])
  .query(ejs.MatchQuery('properties', 'balcony'))
  .scoreMode('multiply');
```

**Comment by smitt04** [comment]
Cool, Thanks.
