### ISSUE TITLE
Timestamps not working

### ISSUE THREAD

**Issue by svperfecta** [fullscale/elastic.js#39]
The documentation for the library states that, by default, timestamps are created for each new document indexed.  In my simple tests, this doesn't seem to be the case.  The documents mention that you should add a mapping, I don't see how to do this in ElasticJS

**Comment by mattweber** [comment]
You need to enable the _timestamp field in elasticsearch.  Unfortunately, we don't currently support creating or updating mapping directly in elasticjs so you will need to use the elasticsearch REST api directly.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html
