### ISSUE TITLE
Autocomplete Support

### ISSUE THREAD

**Issue by heartforit** [fullscale/elastic.js#41]
Hey guys,

i just want to ask a short, but important question.
Is there any chance to get an extendend completion suggester functionality in the sence of elastic search at this great api?

For better understanding what i am talking about follow the link i supposed below:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters-completion.html

I look forward to get an answer on this issue. ;)

Have grate day,
Mr. Love

**Comment by heartforit** [comment]
Thank you very mutch!

**Comment by mattweber** [comment]
Added in master, see my comment in #42 for more information.
