### ISSUE TITLE
Extending elasticjs with custom Facets Dynamically

### ISSUE THREAD

**Issue by mohabusama** [fullscale/elastic.js#54]
Hi,

Is there a way to extend elasticjs lib dynamically to expose custom facets.
something like:

``` javascript
ejs.CustomHistogramFacet
```

The problem I am facing is that **util.js** functions are not exposed, while they are needed within the custom facet.

Thanks

**Comment by mattweber** [comment]
No there is not, you would need to build elastic.js from source with your new Facet inside the src/facets directory so it gets pulled in and has access to the utils.  I will investigate a better way to do this when I start aggregation support.

**Comment by mattweber** [comment]
I think that if you have custom elasticsearch facets you need to support it will be ok if you need to build elastic.js from source to include your custom facet code as described in the previous comments.  There is not an easy way to provide this interface with restructuring the code base.  If there is more requests for this I will revisit it again in the future.  Thanks!
