### ISSUE TITLE
giving preference to a particular field in search

### ISSUE THREAD

**Issue by GJ2511** [fullscale/elastic.js#55]
hi .........
i want to know that is there is any thing possible in elastic search  that while searching in an index on different fields   we can give preference or u can say weightage to a particular field while searching...................
if yes then plz tell me how to implement it as i was using elastic search on windows

**Comment by mattweber** [comment]
Yes, use a Multi-Match query which is supported in elastic.js.

See https://github.com/fullscale/elastic.js/blob/master/src/query/MultiMatchQuery.js and http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html
