### ISSUE TITLE
Add support for Aggregations

### ISSUE THREAD

**Issue by glongman** [fullscale/elastic.js#56]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations.html

A very useful feature and sometime soon aggs will supersede facets.

**Comment by samcday** [comment]
:+1:

**Comment by mattweber** [comment]
Full support for aggregations is now in master.  This includes all the new unreleased aggregations that will be included in the elasticsearch 1.1 release as well.
