### ISSUE TITLE
NumericRange Filter

### ISSUE THREAD

**Issue by seti123** [fullscale/elastic.js#58]
I used the NumericRange Filter for date fields. In the past it worked fine, but with ElasticSearch 1.0/1.1  it behaves wrong. I assume from/to must be replaced with "gte" / "lte" or NumericRangeFilter must be replaced with RangeFilter. 

http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/query-dsl-numeric-range-filter.html

**Comment by mattweber** [comment]
NumericRangeFilter is removed in new versions of elasticsearch.  Use RangeFilter with gt, gte, lt, lte options.
