### ISSUE TITLE
HasChildFilter 

### ISSUE THREAD

**Issue by sampaccoud** [fullscale/elastic.js#59]
I can't figure out how to make a has_child filter with a filter as described in ES documentation (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-has-child-filter.html). 

The HasChildFilter here is expecting a query so the following declaration throws an exception. Is there another way to do it ? 

```
ejs.HasChildFilter(
    ejs.BoolFilter().must([
        ejs.TermsFilter('brand', 'b'), 
        ejs.TermsFilter('model', 'm')
    ])
)
```

**Comment by sampaccoud** [comment]
I solved it myself by wrapping the filter in a constant score query : 

```
ejs.HasChildFilter(
    ejs.ConstantScoreQuery().filter(
        ejs.BoolFilter().must([
            ejs.TermsFilter('brand', 'b'), 
            ejs.TermsFilter('model', 'm')
        ])
    )
)
```

But the question still remains: shouldn't HasChildFilter be able to accept a filter as well ?

**Comment by mattweber** [comment]
Yes it should, I will get this fixed.  Thanks.
