### ISSUE TITLE
Latest version in npm registry

### ISSUE THREAD

**Issue by robertklep** [fullscale/elastic.js#60]
First, thanks for a very useful module :) It makes building queries for ES a lot more structured!

However, the current version in the [npm registry](https://www.npmjs.org/package/elastic.js), v1.1.1, seems to be quite different from the version in the Github repository (also v1.1.1), and it doesn't seem to be very usable (I can't get any of the examples documented in the `README.md` to work, for instance, whereas they work fine for the GH version).

Perhaps it's worth documenting this in the README, and to explain how to install the version from GH using the npm CLI tool:

```
$ npm install fullscale/elastic.js
```

Ideally, the latest version would be posted to the npm repository (npm can tag a publish as being a beta, so it won't be pushed as latest if it isn't yet ready to publish as a proper update).

**Comment by dominicphillips** [comment]
I agree on the README. I think they're already planning the next release. See this https://github.com/fullscale/elastic.js/issues/56 issue.

**Comment by mkw** [comment]
Any updates on this?  (for the bower registry, as well?)  It would be great to use aggregations via this library, in particular, but they are missing in 1.1.1.  A "beta" label would be fine if you're not convinced it's release quality, yet.

**Comment by joafeldmann** [comment]
+1

**Comment by cpdean** [comment]
https://github.com/fullscale/elastic.js/commit/86fa9b74db97fafb16ab46bf2004dbab4f15df77

this is why kibana can't use aggregations from this library

**Comment by mattweber** [comment]
@cpdean Actually, no.  The kibana dev's are writing their own support for aggregations.  I had a PR open but was told it is not needed.

https://github.com/elasticsearch/kibana/pull/1077

**Comment by cpdean** [comment]
ah -- sorry

**Comment by mattweber** [comment]
@cpdean If you are interested in using the latest elastic.js with kibana I opened a new PR.   It would be good to let the kibana team know you are interested in this so they will consider accepting the PR.

https://github.com/elasticsearch/kibana/pull/1222

**Comment by cpdean** [comment]
Hey this is awesome!  If kibana vendors the latest elastic.js, can you bump
the version number so it reflects the changes to ES 1.0 support in the DSL
and the removal of client logic?

**Comment by rabin-a** [comment]
+1 as i can't use Aggregation module

**Comment by ghost** [comment]
+1 Completions + Aggregations

**Comment by arciisine** [comment]
+1 Aggregations.

**Comment by lazdmx** [comment]
+1 Aggregations + SimpleQueryString

**Comment by phjardas** [comment]
There actually is a branch for version 1.1.1, so I assume that the master branch should be version 1.1.2 or 1.2.0 anyway.

However, this repository has not seen any change in the last six months and has three open pull requests. @mattweber, are you guys still maintaining this module?

**Comment by phjardas** [comment]
I have created pull request #74 that includes the latest changes and makes the module work as an npm module again.

**Comment by mattweber** [comment]
Pushed 1.2.0 to NPM.
