### ISSUE TITLE
Cluster ip's in  ejs.client = nc.NodeClient 

### ISSUE THREAD

**Issue by subramanyahs** [fullscale/elastic.js#61]
How to specify multiple ip address for  ejs.client = nc.NodeClient object
example:
ejs.client = nc.NodeClient("server1, server2,server3")

**Comment by mattweber** [comment]
There is no clients anymore.  Please use the official client for connections to elasticsearch and elastic.js on top for query generation.

See:
http://www.elasticsearch.org/guide/en/elasticsearch/client/javascript-api/current/quick-start.html
