### ISSUE TITLE
FunctionScoreQuery missing from version 1.1.1 on npm

### ISSUE THREAD

**Issue by phjardas** [fullscale/elastic.js#63]
When I install the module with npm (from https://registry.npmjs.org/elastic.js/-/elastic.js-1.1.1.tgz) the module is missing FunctionScoreQuery, although the GitHub code contains the code for this and is at version 1.1.1 as well. Could you please double-check the npm deployment process and maybe re-publish the module? Thanks!

**Comment by kfrancoi** [comment]
+1

**Comment by kfrancoi** [comment]
I forked the elastic.js to solve this issue.  The elastic.js file will be copied from the dist repo in the parent folder on the npm install.

I also added the "boost_factor" method to the FunctionScoreQuery complying to the latest ElasticSearch version (1.3.2).

Please find the fork here : https://github.com/Sagacify/elastic.js

**Comment by mattweber** [comment]
Just pushed 1.2.0 to npm which has the function score support.
