### ISSUE TITLE
Minified version does not match source

### ISSUE THREAD

**Issue by SecretAgentKen** [fullscale/elastic.js#66]
The minified version currently in the `dist` folder does not match the full source in the same folder. It seems to be generated from an earlier version. For example, the `source` function for the `Request` object is not available in the minified version but is in elastic.js.

**Comment by phjardas** [comment]
Probably related to issue #63.

**Comment by mattweber** [comment]
Minified is generated from the non-minified version which is directly from the source.  If you pulled from npm you might have an old version.  Please pull 1.2.0 from npm for the latest sources.
