### ISSUE TITLE
How to connect to cluster?

### ISSUE THREAD

**Issue by tsturzl** [fullscale/elastic.js#67]
I haven't found any mention in the guide or documentation of how to connect to a cluster. In fact finding how to connect is generally lacking. It should be one of the first mentioned steps in your guide.

**Comment by babeya** [comment]
There is nothing like connection. Use the official client as you normally do, and when you use search function, fill body attr with the elastic.js request. If you need futher information read official client's documentation. If you need few example you can contact me.

**Comment by mattweber** [comment]
See http://www.elasticsearch.org/guide/en/elasticsearch/client/javascript-api/current/quick-start.html.  There is no connection in elastic.js anymore.  It is now designed to work directly with the official client.
