### ISSUE TITLE
Activity of elastic.js

### ISSUE THREAD

**Issue by mewwts** [fullscale/elastic.js#87]
I stumbled upon this project when I was getting a bit sick of writing out all my queries in my programs. But the fact that it has not received any love for ~ 6 months make me very sceptical towards it. For example, the relatively new `Filters` aggregation is not present in the source. Pull Requests hanging from 2014 is not a good sign either. 

Is this project dead?

**Comment by fvelosa** [comment]
+1

**Comment by waldemarnt** [comment]
+1

**Comment by vaishaks** [comment]
+1

**Comment by mklaber** [comment]
:+1:

**Comment by Asimov4** [comment]
This documentation: http://www.fullscale.co/elasticjs/ points to http://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/index.html as the official javascript elasticsearch client.

It would be nice for the owner of this package @fullscale and @mattweber to add a note in the README redirecting people to https://github.com/elastic/elasticsearch-js

**Comment by Asimov4** [comment]
Actually, based on this conversation: https://github.com/elastic/elasticsearch-js/issues/209, it looks like the two packages are serving different purposes.

**Comment by BeekeeperAlex** [comment]
The last issue was closed in September :/

**Comment by ghost** [comment]
+1

**Comment by ErwanPigneul** [comment]
This fork is updated : https://github.com/ErwanPigneul/elastic.js

Used in https://github.com/pagesjaunes/curiosity

**Comment by mewwts** [comment]
Thanks @ErwanPigneul :+1:
