### ISSUE TITLE
phrase query

### ISSUE THREAD

**Issue by larsvoigt** [fullscale/elastic.js#91]
I want create a query as in the following example:

``` json
{
    "query": {
        "match_phrase": {
            "body": "and WAI-ARIA guidelines for accessible production"
        }
    }
}
```

I had study the elastic.js api but I can't found hints how can I do that.
Can anybody help me?

**Comment by ErwanPigneul** [comment]
Use http://docs.fullscale.co/elasticjs/ejs.MatchQuery.html#ejs.MatchQuery.type

http://docs.fullscale.co/translator/#
ejs.Request()
    .query(ejs.MatchQuery('body', 'and WAI-ARIA guidelines for accessible production').type('phrase'))

**Comment by larsvoigt** [comment]
Thanks @ErwanPigneul for helping me. The translator is great. 
Unfortunately I can't test it at the moment. So I close this issues.
